version: '3'
services:
  qemistree-web:
    networks:
      - default
      - nginx-net
    environment:
      VIRTUAL_HOST: qemistree.ucsd.edu
      VIRTUAL_PORT: 6543
      LETSENCRYPT_HOST: qemistree.ucsd.edu
      LETSENCRYPT_EMAIL: miw023@ucsd.edu

networks:
  nginx-net:
    external:
      name: nginx-net