version: '3'
services:
  qemistree-dash:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: qemistree-dash
    volumes:
      - ./output:/app/output:rw
    ports:
    - "6544:5000"
    networks:
      - default
      - nginx-net
    environment:
      VIRTUAL_HOST: qemistree.ucsd.edu
      VIRTUAL_PORT: 6544
      LETSENCRYPT_HOST: qemistree.ucsd.edu
      LETSENCRYPT_EMAIL: miw023@ucsd.edu
    restart: unless-stopped
    command: /app/run_server.sh


networks:
  nginx-net:
    external:
      name: nginx-net